# Generated by Django 4.1.3 on 2023-02-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('occupancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('copy_of_lease', models.FileField(upload_to='lease_files/')),
                ('aparment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BentTree_API.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('home_address', models.CharField(max_length=50)),
                ('is_renewing', models.BooleanField(default=False, null=True)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BentTree_API.apartment')),
                ('lease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BentTree_API.lease')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BentTree_API.apartment')),
            ],
        ),
    ]
