# Generated by Django 4.1.3 on 2023-02-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BentTree_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tenant_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='BentTree_API.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BentTree_API.lease'),
        ),
    ]
