# Generated by Django 4.1.3 on 2023-02-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BentTree_API', '0002_lease_tenant_id_alter_tenant_lease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rented_as',
            field=models.IntegerField(null=True),
        ),
    ]
