# Generated by Django 4.1.3 on 2023-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BentTree_API', '0003_apartment_rented_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='copy_of_lease',
            field=models.FileField(null=True, upload_to='lease_files/'),
        ),
    ]
