# Generated by Django 4.1.3 on 2023-02-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BentTree_API', '0004_alter_lease_copy_of_lease'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='aparment_id',
            new_name='apartment_id',
        ),
    ]
